name: env3106
channels:
  - conda-forge
  - defaults

dependencies:
    - python=3.10
    
    
    - scikit-learn=1.2.1
    - boto3=1.24.59
    - fastapi=0.92.0
    - uvicorn=0.20.0
    - lightgbm=3.3.5
    - mlflow=2.1.1
    - pandas=1.5.3
    
    - click==8.0.3
    - Flask==2.0.2
    - gunicorn==20.1.0
    - itsdangerous==2.0.1
    - Jinja2==3.0.3
    - MarkupSafe==2.0.1
    - Werkzeug==2.0.2
    
   
    
    
    
    
    
